### ISSUE TITLE
downloading large files hangs

### ISSUE THREAD

**Issue by mk270** [ocaml-attic/mirage.github.com#2]
mk270@marsilio ~> wget http://www.openmirage.org/wiki/tutorial-lwt
--2012-08-09 00:33:47--  http://www.openmirage.org/wiki/tutorial-lwt
Resolving www.openmirage.org... 184.73.180.47
Connecting to www.openmirage.org|184.73.180.47|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58031 (57K) [text/html]
Saving to: `tutorial-lwt'

31% [===========>                           ] 18,377      --.-K/s  eta 10m 22s ^C
mk270@marsilio ~> wget http://www.openmirage.org/wiki/delimcc-vs-lwt
--2012-08-09 00:38:43--  http://www.openmirage.org/wiki/delimcc-vs-lwt
Resolving www.openmirage.org... 184.73.180.47
Connecting to www.openmirage.org|184.73.180.47|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31494 (31K) [text/html]
Saving to: `delimcc-vs-lwt'

58% [=====================>                 ] 18,377      --.-K/s  eta 17s     ^C

Notably, both files at byte 18377

**Comment by avsm** [comment]
could you try the same with 'curl -OL' instead of wget?  Also, what OS is this on?

-anil

**Comment by mk270** [comment]
Ok redone it a few times with curl -OL; same sort of results: the d/l hangs at a particular number of bytes, which is reproducible.

pling: (Debian Linux, at colo): 15561
marsilio (Ubuntu, at home): 18377
marsilio (FreeBSD, at work): 36809
marsilio (OpenIndiana, at work): 58031 (completes)

Now the odd thing about the three incomplete values is that, mod 256, they're all 201. Does that set off any alarm bells for you?

**Comment by avsm** [comment]
I'm preparing a large cohttp update in avsm/ocaml-cohttp (v2-interface
branch) that should comprehensively fix this by respecting all the right
HTTP/11 ways of encoding content-length (or range, or 206 partial
requests).  More shortly...
